### ISSUE TITLE
Prevents auth redirects

### ISSUE THREAD

**Issue by legionio** [darkwinternight/laravel-error-handler#4]
Hi,

For some reason, when using this package, it prevents auth middleware from redirecting non-logged in users to the /login page if they hit a protected route. 

Please see here for more detail:
http://stackoverflow.com/questions/42476857/laravel-5-3-redirect-if-not-logged-in

Laravel 5.3 using laravel-error-handler 1.7

**Comment by darkwinternight** [comment]
Thanks for the report! I will look into it.

**Comment by darkwinternight** [comment]
Fixed by https://github.com/darkwinternight/laravel-error-handler/pull/6.
